os: linux
dist: trusty
language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --no-interaction

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit --verbose

after_success:
  - if [[ "7.2" == "${TRAVIS_PHP_VERSION}" ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
